### ISSUE TITLE
KeyError: 'url' while downloading

### ISSUE THREAD

**Issue by JesseBusman** [xtream1101/humblebundle-downloader#10]
```
Downloading: 2.apk: 100% [==================================================]
Downloading: 3.zip: 100% [==================================================]
Checking bundle: 9
Checking bundle: G
Downloading: s.exe: 100% [==================================================]
Downloading: X.dmg: 100% [==================================================]
Downloading: X.zip: 100% [==================================================]
Downloading: X.sh: 100% [==================================================]
Traceback (most recent call last):
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jesse\AppData\Local\Programs\Python\Python38\Scripts\hbd.exe\__main__.py", line 7, in <module>
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\humblebundle_downloader\cli.py", line 65, in cli
    download_library(
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\humblebundle_downloader\download_library.py", line 64, in download_library
    url = file_type['url']['web']
KeyError: 'url'
```

**Comment by xtream1101** [comment]
This bug was solved, please update to the newest version of the library by running `pip install -U humblebundle-downloader`
