### ISSUE TITLE
Crash on FileNotFoundError

### ISSUE THREAD

**Issue by jeffrey1681** [xtream1101/humblebundle-downloader#11]
Whenever I try to run the script it crashes after a while with a FileNotFoundError (see traceback below). This is using v0.0.8. Any ideas?

Traceback (most recent call last):
  File "c:\users\micro\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\micro\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\micro\Anaconda3\Scripts\hbd.exe\__main__.py", line 7, in <module>
  File "c:\users\micro\anaconda3\lib\site-packages\humblebundle_downloader\cli.py", line 89, in cli
    platform_include=cli_args.platform,
  File "c:\users\micro\anaconda3\lib\site-packages\humblebundle_downloader\download_library.py", line 116, in download_library
    with open(filename, 'wb') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '.\\Humble Double Fine Bundle\\Psychonauts\\Psychonauts.com/psychonauts-linux-05062013-bin'

**Comment by jeffrey1681** [comment]
v0.1.0 appears to have fixed this issue.
