### ISSUE TITLE
Incomplete downloads are not handled

### ISSUE THREAD

**Issue by JesseBusman** [xtream1101/humblebundle-downloader#12]
This download failed, but the partially downloaded file is sitting in its folder as if nothing went wrong.

Possible solutions:
- Files that are current being written should have a .part extension (e.g. BS2RM_3_1_02.apk). The .part extension should be removed when the download has successfully completed.
- Catch exceptions that cause a download to fail. Delete the partially downloaded file.
- Catch exceptions that cause a download to fail. Add a .part extension to the partially downloaded file.

```

Downloading: Broken Sword 2 - The Smoking Mirror/BrokenSword2_Linux_1395095896.zip: 100% [==================================================]
Downloading: Broken Sword 2 - The Smoking Mirror/BrokenSword2_windows_1395095896.zip: 100% [==================================================]
Downloading: Broken Sword 2 - The Smoking Mirror/BrokenSword2_mac_1396042209.dmg: 100% [==================================================]
Traceback (most recent call last):Smoking Mirror/BS2RM_3_1_02.apk: 30% [===============                                   ]
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\urllib3\response.py", line 425, in _error_catcher
    yield
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jesse\AppData\Local\Programs\Python\Python38\Scripts\hbd.exe\__main__.py", line 7, in <module>
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\humblebundle_downloader\cli.py", line 89, in cli
    download_library(
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\humblebundle_downloader\download_library.py", line 128, in download_library
    for data in item_r.iter_content(chunk_size=4096):  # noqa E501
  File "c:\users\jesse\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Comment by azuravian** [comment]
Workaround, until fixed, is to rerun.  The json cache file that is created in the download folder does not mark a file as downloaded until the download is complete, so it will overwrite that apk, but will skip everything else that was already downloaded successfully.
