### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by tmcarr** [xtream1101/humblebundle-downloader#26]
I'm trying to use this tool, but I'm running into a syntax error:

```$ hbd download --cookie-file ~/Desktop/cookies-humblebundle-com.txt --library-path ~/Downloads/HBDownloads --progress
Traceback (most recent call last):
  File "/usr/local/bin/hbd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/humblebundle_downloader/cli.py", line 97, in cli
    from .download_library import DownloadLibrary
  File "/usr/local/lib/python2.7/site-packages/humblebundle_downloader/download_library.py", line 338
    ), end='\r')
          ^
SyntaxError: invalid syntax```

**Comment by xtream1101** [comment]
This requires python3, you are using python2. When you install the library
try using pip3 rather then just pip
