### ISSUE TITLE
Unable to download user-data, cookies missing?

### ISSUE THREAD

**Issue by WhaleJ84** [xtream1101/humblebundle-downloader#29]
Using the recommended Firefox Export Cookies extension to download the cookies results with the following error:

```
Traceback (most recent call last):
  File "/home/james/.local/bin/hbd", line 8, in <module>
    sys.exit(cli())
  File "/home/james/.local/lib/python3.8/site-packages/humblebundle_downloader/cli.py", line 82, in cli
    DownloadLibrary(
  File "/home/james/.local/lib/python3.8/site-packages/humblebundle_downloader/download_library.py", line 57, in start
    self.purchase_keys = self.purchase_keys if self.purchase_keys else self._get_purchase_keys()  # noqa: E501
  File "/home/james/.local/lib/python3.8/site-packages/humblebundle_downloader/download_library.py", line 380, in _get_purchase_keys
    raise Exception("Unable to download user-data, cookies missing?")
Exception: Unable to download user-data, cookies missing?
```

I managed to get around this particular issue by using the [Cookie Quick Manager](https://addons.mozilla.org/en-GB/firefox/addon/cookie-quick-manager/?src=search) plugin and changing the output to Netscape in the settings.

**Comment by xtream1101** [comment]
I am not able to reproduce this issue. the firefox extension exports the cookies correctly for me. Glade you found one that worked for you though.

**Comment by WashJotson** [comment]
Exactly the same issue here, Firefox 82.0 on Mac
