### ISSUE TITLE
Script crash when Humble Bundle returns error 404

### ISSUE THREAD

**Issue by alferezkururu966** [xtream1101/humblebundle-downloader#31]
Hi, I discovered this scrip a few weeks ago and i'm loving it, the good feeling that comes from having all your files in your own hard drive instead of depending on someone to keep em online.

Praise aside I found a "bug", I noticed that the script crashed while downloading, not a big deal, ran it again and didn't thing twice of it, but today i noticed that the thing is crashing on an specific bundle, so i looked up the key for the bundle it was having trouble with and found it was "HUMBLE OVERWHELMINGLY POSITIVE BUNDLE 2", grabbed the key and started testing.

It crashed as soon as it finished downloading it and I went onto the humble page to try to download it manually and voila, the file is missing. (also tried the torrent file and is also corrupted)

I will now provide the error code:

`I:\Humble Bundle>hbd download -c cookies.txt -l "Tests" --progress -k [Bundle key here] --update
Checking bundle: Humble Overwhelmingly Positive Bundle 2
Downloading: Tests\Humble Overwhelmingly Positive Bundle 2\SOMA\SOMA_Windows_v110.zip
        100% [==================================================]
Downloading: Tests\Humble Overwhelmingly Positive Bundle 2\SOMA\SOMA_Linux_v110.zip
        100% [==================================================]
Downloading: Tests\Humble Overwhelmingly Positive Bundle 2\SOMA\SOMA_Mac_v110_ModLauncher_Fix.zip
        100% [==================================================]
Downloading: Tests\Humble Overwhelmingly Positive Bundle 2\SOMA\ModLauncher.zip
        100% [==================================================]
Downloading: Tests\Humble Overwhelmingly Positive Bundle 2\Momodora - Reverie Under the Moonlight\momodora_reverieunderthemoonlight_windows.zip
        100% [==================================================]
Traceback (most recent call last):
  File "C:\Users\alfer\AppData\Local\Programs\Python\Python38\Scripts\hbd-script.py", line 11, in <module>
    load_entry_point('humblebundle-downloader==0.3.2', 'console_scripts', 'hbd')()
  File "c:\users\alfer\appdata\local\programs\python\python38\lib\site-packages\humblebundle_downloader\cli.py", line 82, in cli
    DownloadLibrary(
  File "c:\users\alfer\appdata\local\programs\python\python38\lib\site-packages\humblebundle_downloader\download_library.py", line 66, in start
    self._process_order_id(order_id)
  File "c:\users\alfer\appdata\local\programs\python\python38\lib\site-packages\humblebundle_downloader\download_library.py", line 207, in _process_order_id
    self._process_product(order_id, bundle_title, product)
  File "c:\users\alfer\appdata\local\programs\python\python38\lib\site-packages\humblebundle_downloader\download_library.py", line 272, in _process_product
    'url_last_modified': product_r.headers['Last-Modified'],
  File "c:\users\alfer\appdata\local\programs\python\python38\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'last-modified'`

If I can provide any other useful information I would love to help.

**Comment by alferezkururu966** [comment]
Forgot to mention, I have not contacted humble bundle about the issue in order to have a "known fail" to test with in case it would be necessary.
I will contact then when the issue is resolved though.
