### ISSUE TITLE
KeyError: 'last-modified'

### ISSUE THREAD

**Issue by derekmurawsky** [xtream1101/humblebundle-downloader#34]
First off, thank you for this app. It's worked really well to download the majority of my library. 

After many (18-20+) hours of downloading, the downloader crashed with this error:

```
Checking bundle: Humble Image Comics Bundle 2 - Image Firsts
Checking bundle: Humble Comics Bundle - Image Comics featuring Creators OWN Worlds
Traceback (most recent call last):
  File "/usr/local/bin/hbd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/humblebundle_downloader/cli.py", line 82, in cli
    DownloadLibrary(
  File "/usr/local/lib/python3.9/site-packages/humblebundle_downloader/download_library.py", line 66, in start
    self._process_order_id(order_id)
  File "/usr/local/lib/python3.9/site-packages/humblebundle_downloader/download_library.py", line 207, in _process_order_id
    self._process_product(order_id, bundle_title, product)
  File "/usr/local/lib/python3.9/site-packages/humblebundle_downloader/download_library.py", line 272, in _process_product
    'url_last_modified': product_r.headers['Last-Modified'],
  File "/usr/local/lib/python3.9/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'last-modified'
```

I tried to resume but it broke at the exact same spot. Any thoughts? Can I provide any specifics to help debug? Is there any way to skip this one so I can continue downloading the rest?

**Comment by derekmurawsky** [comment]
By setting `export HBD_LOGLEVEL=debug` I was able to confirm the item - nowheremen_optimized.pdf. Trying to download it manually through the website confirmed the file is actually missing. 
![image](https://user-images.githubusercontent.com/3741839/106317924-fe5d0180-623c-11eb-94fa-474f047d7ccd.png)

![image](https://user-images.githubusercontent.com/3741839/106317948-0ae15a00-623d-11eb-8ed6-93602bf3dd6b.png)

Can you suggest how to add the relevant error handling in this section to continue with file downloads in the event of an error like this?

**Comment by derekmurawsky** [comment]
After line 267, you can insert the following to check the status code. It worked for me, but might not be good to check a 200 in case 300s are ever returned. 

```
                if cache_file_info != {} and self.update is not True:
                    # Do not care about checking for updates at this time
                    continue

                try:
                    product_r = self.session.get(url, stream=True)
                except Exception:
                    logger.error("Failed to download {url}".format(url=url))
                    continue

                # Added by Derek
                if product_r.status_code != 200:
                    continue
                # End Add

                logger.debug("Item request: {product_r}, Url: {url}"
                             .format(product_r=product_r, url=url))
                file_info = {
                    'url_last_modified': product_r.headers['Last-Modified'],
                }
```
