### ISSUE TITLE
cookies missing

### ISSUE THREAD

**Issue by MrSVCD** [xtream1101/humblebundle-downloader#40]
Hi, 
I fed the script with my key (-s) and the script crashed.
am I missing something?

```
Traceback (most recent call last):
  File "~/.local/bin/hbd", line 8, in <module>
    sys.exit(cli())
  File "~/.local/lib/python3.8/site-packages/humblebundle_downloader/cli.py", line 84, in cli
    DownloadLibrary(
  File "~/.local/lib/python3.8/site-packages/humblebundle_downloader/download_library.py", line 63, in start
    self.purchase_keys = self.purchase_keys if self.purchase_keys else self._get_purchase_keys()  # noqa: E501
  File "~/.local/lib/python3.8/site-packages/humblebundle_downloader/download_library.py", line 397, in _get_purchase_keys
    raise Exception("Unable to download user-data, cookies missing?")
Exception: Unable to download user-data, cookies missing?
```

**Comment by ccoenen** [comment]
this should be in the readme somewhere! Thanks for sharing the explanation :-)

It should be noted that windows batch (or plain windows cmd.exe) escape the `"` differently, here I had to

`--session-auth """whatever I found in my browser"""`

so literally three double quotes on each side. The outer ones keep the string together, and the inner pair then is actually an escaped double quote (basically, on windows `""` does the same what `\"` does in most linux shells)
