### ISSUE TITLE
Can't launch hbd command

### ISSUE THREAD

**Issue by wildcardjoker** [xtream1101/humblebundle-downloader#56]
After installing using `pip install humblebundle-downloader`, I can't run hbd.

I'm running the commands in a PowerShell session on Windows 10, and python 3.9.

`hbd --help` returns the error `The term 'hbd' is not recognized as the name of a cmdlet, function, script file, or operable program.`.
`python hbd` returns the error `C:\Users\wildcardjoker\AppData\Local\Microsoft\WindowsApps\python.exe: can't open file 'C:\Users\wildcardjoker\source\humblebundle-downloader\build\lib\humblebundle_downloader\hbd': [Errno 2] No such file or directory`

It's probably a very basic thing that I'm missing, however I'm not very familiar with python and am unsure how to proceed.

**Comment by wildcardjoker** [comment]
It appears that I needed to add `\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\Scripts` to my `PATH` variable.

`hbd.exe` now runs, however I'm receiving a 'KeyError: 'hbd'` error instead:

```
Traceback (most recent call last):
  File "C:\users\wildcardjoker\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\Scripts\hbd-script.py", line 33, in <module>
    sys.exit(load_entry_point('hbd==0.4.0', 'console_scripts', 'hbd')())
  File "C:\Users\wildcardjoker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cli.py", line 310, in main
    cli(default_map=load_config(CONFIG_FILE))
  File "C:\Users\wildcardjoker\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cli.py", line 305, in load_config
    return {'download': config[CONFIG_SECTION]}
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'hbd'
```

**Comment by wildcardjoker** [comment]
And my issue is resolved. For anyone else experiencing this issue, `hbd` won't work if you have **installed Python via the Windows Store**.

After I installed Python using the standard installer, everything works fine.
